### PR TITLE
Feature/windows scripts

### PR DESCRIPTION
**Pull request by JonasGilg**
This creates clang-format and clang-tidy PowerShell scripts.

### CODE REVIEW

**Comment by Schneegans** [comment]
I'll test those as soon as possible. In the meantime - what do you think about moving all those formatting scripts to the tools directory?

**Comment by JonasGilg** [comment]
> [...] - what do you think about moving all those formatting scripts to the tools directory?

That's a good idea.

**Comment by Schneegans** [comment]
I just tested this and it seems to work properly. Just two observations:
* The `CMAKE_EXPORT_COMPILE_COMMANDS` only works with ninja. Therefore the clang-tidy script only works with this generator as well. Should we point this out somewhere? At least in the comments in the file?
* Not really related to this PR, but I just noticed that the new-plugin-script behaves kind of weird when no parameter is passed. Maybe it could either ask for the plugin name or print a warning / help message.

What do you think?

**Comment by Schneegans** [comment]
Btw, the comment percentage check must fail for this PR as the script got moved. So it cannot find it in the base branch.

**Comment by JonasGilg** [comment]
> * The `CMAKE_EXPORT_COMPILE_COMMANDS` only works with ninja. Therefore the clang-tidy script only works with this generator as well. Should we point this out somewhere? At least in the comments in the file?

Yeah I'll add that to the description.

> * Not really related to this PR, but I just noticed that the new-plugin-script behaves kind of weird when no parameter is passed. Maybe it could either ask for the plugin name or print a warning / help message.

When I call the New-Plugin.ps1 without parameters I get a prompt asking for the name by default:
```powershell
PS C:\C++\cs-debug> .\tools\New-Plugin.ps1

cmdlet New-Plugin.ps1 at command pipeline position 1
Supply values for the following parameters:
Name[0]:
```

**Comment by Schneegans** [comment]
> When I call the New-Plugin.ps1 without parameters I get a prompt asking for the name by default:
> 
> ```powershell
> PS C:\C++\cs-debug> .\tools\New-Plugin.ps1
> 
> cmdlet New-Plugin.ps1 at command pipeline position 1
> Supply values for the following parameters:
> Name[0]:
> ```

Yes, it does, but if I enter a name, it keeps asking for other paramters called `Name`...?

**Comment by JonasGilg** [comment]
> > When I call the New-Plugin.ps1 without parameters I get a prompt asking for the name by default:
> > ```powershell
> > PS C:\C++\cs-debug> .\tools\New-Plugin.ps1
> > 
> > cmdlet New-Plugin.ps1 at command pipeline position 1
> > Supply values for the following parameters:
> > Name[0]:
> > ```
> 
> Yes, it does, but if I enter a name, it keeps asking for other paramters called `Name`...?

Ah, I see. I think I fixed that with the last commit. I accidentally specified the `Name` parameter as an array of strings.

**Review by Schneegans — APPROVED** [review]

**Comment by Schneegans** [comment]
It works now!

**Pull request merged**
