### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by Schneegans**
This updates most of our submodules to the current versions. Additionally, our CI jobs on GitHub now run on Ubuntu 20.04.

### CODE REVIEW

**Comment by JonasGilg** [comment]
While compiling spdlog I get the error below. Maybe we can disable the compilation of tests?

```
Building and installing spdlog ...

-- Eclipse version is set to 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
-- Build spdlog: 1.5.0
-- Build type: Release
-- Generating examples
-- Generating tests
-- Checking for module 'libsystemd'
--   No package 'libsystemd' found
-- Generating install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gilg_jn/cosmoscout-vr/build/linux-externals-Release/spdlog
[ 25%] Built target spdlog
[ 33%] Built target example
[ 40%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/test_create_dir.cpp.o
[ 40%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/main.cpp.o
[ 44%] Building CXX object tests/CMakeFiles/spdlog-utests.dir/test_errors.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/gilg_jn/cosmoscout-vr/externals/spdlog/tests/catch.hpp:6323,
                 from /home/gilg_jn/cosmoscout-vr/externals/spdlog/tests/main.cpp:2:
/home/gilg_jn/cosmoscout-vr/externals/spdlog/tests/catch.hpp:9041:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 9041 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
gmake[2]: *** [tests/CMakeFiles/spdlog-utests.dir/build.make:199: tests/CMakeFiles/spdlog-utests.dir/main.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:190: tests/CMakeFiles/spdlog-utests.dir/all] Error 2
gmake: *** [Makefile:182: all] Error 2
```

**Comment by Schneegans** [comment]
On which compiler does this happen? But sure, we can do this. It would also improve the build time by some milliseconds :wink:. I'll defer pushing this until the CI is finished, I guess some more issues will pop up...

**Comment by JonasGilg** [comment]
> On which compiler does this happen? 

GCC-11 😬

**Comment by JonasGilg** [comment]
On Windows I get the following error when building curl:

```
CMake Error at CMakeLists.txt:360 (message):
  The option CMAKE_USE_WINSSL was renamed to CURL_USE_SCHANNEL
```

**Comment by Schneegans** [comment]
Finally. Does it work on your end? I had to downgrade glm and gli again as they finally fixed the quaternion constructor order from WXYZ to XYZW. But this change would require a lot of changes to our code base and some very intense testing thereafter... Also downstream projects such as VESTEC would suffer from this, I guess.

**Comment by JonasGilg** [comment]
On Windows I get the following error. I use Visual Studio 2017:

```
Building and installing civetweb ...

-- The C compiler identification is MSVC 19.16.27045.0
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target architecture - x86_64
-- Enabling tests in the build - OFF
-- Thread Stack Size - 102400
-- Enabling server executable - OFF
-- Serve no static files - OFF
-- Disable CGI support - OFF
-- Disable caching support - OFF
-- C++ wrappers - On
-- IP Version 6 - OFF
-- Websockets support - OFF
-- Server statistics support - OFF
-- Memory Debugging - OFF
-- ASAN in debug mode - ON
-- Force x32 / x64 architecture - OFF
-- Lua CGI support - OFF
-- zlib support - OFF
-- Executable installation - ON
-- Build if there are warnings - ON
-- Duktape CGI support - OFF
-- SSL support - ON
-- Compile for OpenSSL 1.0 API - OFF
-- Compile for OpenSSL 1.1 API - ON
-- Dynamically load SSL libraries - ON
-- Configuring C Compiler
-- Performing Test NO_DIAGNOSTICS_PRODUCED
-- Performing Test NO_DIAGNOSTICS_PRODUCED - Success
-- Configuring C++ Compiler
-- Performing Test -Wno-reserved-id-macros
-- Performing Test -Wno-reserved-id-macros - Failed
-- Could NOT find WinSock (missing: WINSOCK_LIBRARIES)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Could NOT find LibRt (missing: LIBRT_LIBRARIES)
-- Could NOT find LibDl (missing: LIBDL_LIBRARIES LIBDL_INCLUDE_DIRS)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/C++/cs-gh/build/windows-externals-Release/civetweb
[1/5] Building C object src\CMakeFiles\civetweb-c-library.dir\civetweb.c.obj
FAILED: src/CMakeFiles/civetweb-c-library.dir/civetweb.c.obj
C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo -DCIVETWEB_DLL_EXPORTS -DOPENSSL_API_1_1 -DUSE_STACK_SIZE=102400 -Dcivetweb_c_library_EXPORTS -IC:\C++\cs-gh\externals\civetweb\include /DWIN32 /D_WINDOWS /W3 -std=c11 -std=c99 -std=c89 -Wall -Wextra -Wshadow -Wconversion -Wmissing-prototypes -Weverything -Wparentheses /W4 -Wno-padded -Wno-unused-macros -Wno-format-nonliteral -Wno-cast-qual /Wd4820 -pedantic-errors -fvisibility=hidden /MD /O2 /Ob2 /DNDEBUG -fstack-protector-strong /showIncludes /Fosrc\CMakeFiles\civetweb-c-library.dir\civetweb.c.obj /Fdsrc\CMakeFiles\civetweb-c-library.dir\ /FS -c C:\C++\cs-gh\externals\civetweb\src\civetweb.c
cl : Befehlszeile error D8021 : Ungültiges numerisches Argument /Wextra.
[2/5] Building CXX object src\CMakeFiles\civetweb-cpp.dir\CivetServer.cpp.obj
FAILED: src/CMakeFiles/civetweb-cpp.dir/CivetServer.cpp.obj
C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DCIVETWEB_CXX_DLL_EXPORTS -DCIVETWEB_DLL_IMPORTS -DOPENSSL_API_1_1 -DUSE_STACK_SIZE=102400 -Dcivetweb_cpp_EXPORTS -IC:\C++\cs-gh\externals\civetweb\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc -std=c++14 -std=c++11 -std=c++98 -Wall -Wextra -Wshadow -Wmissing-prototypes -Weverything /W4 -Wno-padded /Wd4820 -Wno-unused-macros -Wno-format-nonliteral -pedantic-errors -fvisibility=hidden /MD /O2 /Ob2 /DNDEBUG -fstack-protector-strong -flto /showIncludes /Fosrc\CMakeFiles\civetweb-cpp.dir\CivetServer.cpp.obj /Fdsrc\CMakeFiles\civetweb-cpp.dir\ /FS -c C:\C++\cs-gh\externals\civetweb\src\CivetServer.cpp
cl : Befehlszeile error D8021 : Ungültiges numerisches Argument /Wextra.
```

**Review by JonasGilg — APPROVED** [review]

**Pull request merged**
