### PR TITLE
Add more flexible initSlider functions to the GuiApi

### LINKED ISSUE #214: Add more slider initialization options
## The Problem
I sometimes need to create non-linear sliders in the UI.
It would be cool to have a utility function similar to initSlider, that initializes a non-linear noUISlider and sets up the callback.

## The Solution
Add addtional initSlider functions to the API that allow passing a range object or arbitrary options for noUISlider.

## The Alternatives
The sliders could also be initialized manually everytime a non-linear slider is needed.
This would also require the callback to be set up manually.

Alternatively, a unified initSlider function could be implemented.
That function would need to decide what kind of slider to create based on the passed parameters.

### PR DESCRIPTION
**Pull request by TheFridge76**
Resolves #214

### CODE REVIEW

**Comment by Schneegans** [comment]
Looks good to me. I will try to fix the CI build in `develop`, then we can test whether the checks pass for this PR!

**Comment by Schneegans** [comment]
Could you please merge `develop` and see whether the checks succeed?

**Comment by Schneegans** [comment]
Is this PR Ready for Review? Or are you planning to add something?

**Comment by TheFridge76** [comment]
This is ready for review

**Review by Schneegans — APPROVED** [review]

**Comment by Schneegans** [comment]
Thank you!

**Pull request merged**
